export const ADD_TODO = 'ADD_TODO'
export const REMOVE_TODO = 'REMOVE_TODO'
export const UPDATE_TODO = 'UPDATE_TODO'
export const FETCH_DATA = 'FETCH_DATA'
export const UPLOAD_TODOS_FROM_REMOTE = 'UPLOAD_TODOS_FROM_REMOTE'
export const COMPLETE_TODO = 'COMPLETE_TODO'

export const SET_FILTER = 'SET_FILTER'